In [1]:
import tensorflow as tf
from tensorflow import keras
import keras.backend as K

import numpy as np

2022-12-14 14:47:10.637958: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-14 14:47:10.732455: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-12-14 14:47:10.732470: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-12-14 14:47:11.289688: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-

# Custom Layer 
computes whether input point is on the right side of the Plane

In [60]:
class InHull(tf.keras.layers.Layer):
    def __init__(self, units=1): # one output
        super().__init__()
        self.units = units
    
    def build(self, input_shape):
        w_init=tf.random_normal_initializer()
        nHplanes = input_shape[-1] + 1
        nDims = input_shape[-1]
        self.w = tf.Variable(initial_value = w_init(shape = (nHplanes, nDims),
                                                    dtype="float32"), 
                             trainable = True)
        print("Weights in layer: ", self.w)
        #print("length of layer: ", len(self.w)/2)
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(initial_value = b_init(shape = (nHplanes, nDims),
                                                    dtype = "float32"), 
                             trainable = True)
        print("Bias in Layer: ", self.b)

    def call(self, inputs):
        # print("weights:", self.w)
        # print("biases:", self.b)
        # print("inputs:", inputs)
        # ntpoint = inputs
        # point = np.transpose(ntpoint)
        # print("point:", point)
        # dots = [K.sum(self.w[i] * (self.b[i] - point), axis = -1, keepdims = True) for i in range(4)]#range(len(self.w)/2)]
        # print("dots", dots)
        res = K.sum(self.w[0] * (self.w[1] - inputs), axis = -1, keepdims = True)
        # print("here=", res)
        # print(res)
        #return tf.Variable[0.0]
        return K.sum(self.w[0] * (self.w[1] - inputs), axis = -1, keepdims = True)
        # return K.batch_dot(inputs * self.w, axis =-1,keepdims = True) + self.b

In [66]:
def in_convex_hull(point, plane_point, plane_normal):
    if np.dot(plane, (point - a)) == 1:
        return true
    return false

def custom_loss(actual, pred):
    loss = 0
    return loss

model = keras.Sequential([InHull(1)])
model.compile(optimizer='Adam', loss='BinaryCrossentropy', metrics = ["accuracy"])

xs = np.array([[ 0.0, 0.0, 0.0],
               [ 1.0, 1.0, 1.0],
               [-1.0,-1.0,-1.0],
               [ 1.0, 0.0, 0.0],
               [ 0.0, 1.0, 0.0],
               [ 0.0, 0.0, 1.0]])
ys = np.array([[1],
               [0],
               [0],
               [0],
               [0],
               [0]])

# xs = np.array([[ 0.0, 0.0, 0.0]])
# ys = np.array([[1]])

history = model.fit(xs, ys, epochs=10000, batch_size=1, verbose = 0)

[[ 0.  0.  0.]
 [ 1.  1.  1.]
 [-1. -1. -1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
Weights in layer:  <tf.Variable 'in_hull_27/Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.01864201, -0.05431065,  0.09596236],
       [-0.05934132,  0.02205252,  0.03555093],
       [-0.03432096, -0.01854827,  0.09575459],
       [-0.01217742,  0.06513804, -0.05324098]], dtype=float32)>
Bias in Layer:  <tf.Variable 'in_hull_27/Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>


In [63]:
xs = np.array([[ 0.0, 0.0, 0.0]])

model.predict(xs)

1/1 [==============================] - 0s 56ms/step


array([[-0.00564666]], dtype=float32)

In [6]:
print("Weights: ", model.layers[0].get_weights()[0])
print("Biases: ", model.layers[0].get_weights()[1])

Weights:  [[ 0.04484339 -0.01542579  0.01255676]
 [ 0.02095187  0.01758021 -0.02743695]
 [-0.02538426  0.02119865  0.0322537 ]
 [-0.01514442  0.06497443 -0.01204634]]
Biases:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [49]:
weight = tf.Variable([[-0.02217364,  0.02388768, -0.01642606],
       [ 0.0470141 , -0.1108605 ,  0.06211011],
       [ 0.00317579,  0.00729559,  0.13069701],
       [-0.0888112 ,  0.11896175, -0.07816519]])
bias = tf.Variable([[1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
input = tf.Variable([0.0,0.0,0.0])
point = input
print(weight, bias, point)
print("stop")
dots = tf.Variable([K.sum(weight[i] * (bias[i] - point), axis = -1, keepdims = True) for i in range(4)])#range(len(self.w)/2)]
# dots = dots/dots
print(dots[1] == 1)

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[-0.02217364,  0.02388768, -0.01642606],
       [ 0.0470141 , -0.1108605 ,  0.06211011],
       [ 0.00317579,  0.00729559,  0.13069701],
       [-0.0888112 ,  0.11896175, -0.07816519]], dtype=float32)> <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)> <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>
stop
tf.Tensor([False], shape=(1,), dtype=bool)


In [6]:
xs = np.array([np.random.rand(1000,3) for i in range(1)])[0]
print(xs)
xy = np.array( for x in xs)

[[0.88724768 0.7934657  0.6324761 ]
 [0.83078754 0.44004283 0.635758  ]
 [0.33647652 0.92324053 0.86827978]
 ...
 [0.18818799 0.73330666 0.39180892]
 [0.98370983 0.93480106 0.39973269]
 [0.12962338 0.76257981 0.94893442]]
